spring.application.name=bank_system_producer

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

spring.kafka.producer.properties.schema.registry.url=http://localhost:8081
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.acks=all

spring.datasource.url=jdbc:postgresql://localhost:2345/bank_system_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=db/changelog/db.changelog-master.xml
